name: 'Another action'

inputs:
  version:
    description: "The version of the package to assign."
    required: true

runs:
  using: "composite"

  steps:
    - run: node ${{ github.action_path }}/main.mjs "${{ inputs.version }}"
      shell: bash
