name: 'Customer outs'
description: 'Csadasd'
inputs:
  customers:
    description: 'The customers'
    required: false
runs:
  using: "composite"
  steps:

    - uses: actions/github-script@v6
      name: Print customers
      with:
        result-encoding: string
        script: |
          const customers = core.getInput('customers');
          core.info('customers');
          core.info(customers);
