name: 'Customer outs'
description: 'Csadasd'
inputs:
  customer:
    description: 'The customer'
    required: false
  customers:
    description: 'The customers'
    required: false
runs:
  using: "composite"
  steps:

    - uses: actions/github-script@v6
      name: Print customers
      with:
        result-encoding: string
        script: |
          const customers = ${{ inputs.customers }};
          const customer = ${{ inputs.customer }};
          core.info(`customers: ${customers}`);
          core.info(`customer: ${customer}`);
