name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
  
    - shell: bash
      run: |
        echo ${{ env.HELLOWITHYOU }}
      
    - run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      shell: bash
      
    - uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: "5.0.400"
        
    - run: echo Hello ${{ inputs.who-to-greet }} ${{ env.GITHUB_SHA_SHORT }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash     
