name: Caller

on:
  workflow_dispatch:
    inputs:
      names:   
        description: json string names array
        required: true
    
jobs: 

  call-calleme:
    uses: ./.github/workflows/callme.yml
    strategy:
      fail-fast: false
      matrix: 
        name: ${{ fromJSON(github.event.inputs.names) }}
    with:
      name: ${{ matrix.name }}
