name: Caller

on:
  workflow_dispatch:
    inputs:
      name:   
        description: Just some name
        required: true
    
jobs: 

  call-calleme:
    uses: ./.github/workflows/c/callme.yml
    with:
      name: ${{ github.event.inputs.name }}
