name: Caller

on:
  workflow_dispatch:
    inputs:
      name:   
        description: Just some name
        required: true
    
jobs: 

  call-calleme:
    uses: ./.github/workflows/callme.yml
    strategy:
      fail-fast: false
    with:
      name: ${{ github.event.inputs.name }}
