name: Caller

on:
  workflow_dispatch:
    inputs:
      names:   
        description: json string names array
        required: true
    
jobs: 

  call-calleme:
    strategy:
      fail-fast: false
      matrix: 
        something: ${{ fromJson(github.event.inputs.names) }}
    uses: ./.github/workflows/callme.yml
    with:
      name: '${{ matrix.something }}'
