name: Caller

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'A name'
        type: string
        required: true
  
    
jobs: 

  call-callme:
    uses: ./.github/workflows/callme.yml
    strategy:
      matrix:
        something: [a, b]
    with:
      name: '${{github.event.inputs.name}}'
