name: Caller

on:
  workflow_dispatch:
    inputs:
      names:   
        description: json string names array
        type: string
        required: true
    
jobs: 

  call-calleme:
    strategy:
      fail-fast: false
      matrix: 
        something: [a, b, c]
    uses: ./.github/workflows/callme.yml
    with:
      name: '${{ matrix.something }}'
