name: Caller

on:
  workflow_dispatch:
    
jobs: 

  call-callme:
    strategy:
      fail-fast: false
      matrix: 
        ref: [main, develop]
    uses: ./.github/workflows/callme.yml@${{ matrix.ref }}
    with:
      name: 'hello from ${{ matrix.ref }}'
