name: Do a simple thing

on: 
  workflow_dispatch:
    inputs:
      issue_number:
        description: the issue number to log
        required: false 
      pull_number:
        description: the pull request number to log
        required: false 
      release_tag:
        description: the tag related to a release to log
        required: false 
    
jobs:

   log-pr:
    runs-on: ubuntu-latest
    if: github.event.inputs.pull_number
    name: Log a pull request by number
    
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull = await github.rest.pulls.get({ owner, repo, pull_number: ${{ github.event.inputs.pull_number }} });
            console.log({ pull });

   log-issue:
    runs-on: ubuntu-latest
    if: github.event.inputs.issue_number
    name: Log an issue by number
    
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue = await github.rest.issues.get({ owner, repo, issue_number: ${{ github.event.inputs.issue_number }} });
            console.log({ issue });

   log-release:
    runs-on: ubuntu-latest
    if: github.event.inputs.release_tag
    name: Log a release by tag
    
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const release = await github.rest.repos.getReleaseByTag({ owner, repo, tag: '${{ github.event.inputs.release_tag }}' });
            console.log({ stringifiedBody: JSON.stringify(release.body) })
            console.log({ release });
      
   set-filename-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set filename name
        run: |
          echo "action_state=$(find . -name '*.txt' | head -n 1)" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.action_state }}"
