name: Do a simple thing

on: 
  workflow_dispatch:
    inputs:
      pull_number:
        description: the pull request number to log
        required: true 
    
jobs:

   job:
    runs-on: ubuntu-latest
    if: github.event.inputs.pull_number
    name: Log a pull request by number
    
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull = await github.rest.pulls.get({ owner, repo, pull_number: ${{ github.event.inputs.pull_number }} });
            console.log({pull});
