name: Do the thing

on: 
  workflow_dispatch:
  
jobs:

  checkout-job:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: Checkout files except .github
        uses: actions/checkout@v4
      
      - name: List dirs
        run: |
          ls -la .
          ls -la .github

      - run: |
          git checkout origin/develop .github
      
      - name: List dirs
        run: |
          ls -la .
          ls -la .github
