name: Do the thing

on: 
  workflow_dispatch:
    inputs:

      environment:
        description: Environment
        type: environment
        required: true
  
jobs:

  checkout-job:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: Checkout files except .github
        uses: actions/checkout@v4
      
      - name: List dirs
        run: |
          ls -la .
          ls -la .github

      - run: |
          git fetch origin develop --depth 1
          git checkout origin/develop --no-overlay -- .github
      
      - name: List dirs
        run: |
          ls -la .
          ls -la .github
      
      - name: echo env var
        run: |
          echo "${{ vars.t1 }}"
          
