name: PR Labeler

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'The name'     
        required: true
        default: 'Bob' 

jobs:
  dothehello:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/hello
        with:
          name: ${{ github.event.inputs.name }}
            
