name: Do the thing

on: 
  workflow_dispatch:
#     inputs:
#       name:
#         description: 'The name'     
#         required: true
#         default: 'Bob' 

jobs:
#   dothehello:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set the vars
#         uses: ./.github/actions/hello
#         with:
#           name: ${{ github.event.inputs.name }}
          
          
#       - name: Run the hello input thing
#         uses: ./.github/actions/hello-world-composite
#         with:
#           who-to-greet: 'someone'
          
#       - name: Echo the vars
#         run: |
#           echo 'HELLOWITHYOU'
#           echo ${{ env.HELLOWITHYOU }}


#   doanotherthing:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 16.x
#       - uses: ./.github/actions/anotheraction
#         with:
#           version: "someversion"


  dothejsthing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/github-script@v6
        id: getcustomer
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const path = require('path');
            const data = fs.readFileSync(path.join(${{github.workspace}}, 'test.json'));
            let parsed = JSON.parse(data);
            return parsed.customer;
            
      - name: Get result
        run: echo "${{steps.getcustomer.outputs.result}}"
