name: Do the thing

on: 
  workflow_dispatch:
    inputs:
      dojob2:
        description: Should job2 be run
        type: boolean
        default: false
        required: true 
      test2ReleaseName:
        description: Do a release to test2 with this name
        type: string
        required: false 
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/github-script@v6
        id: getcustomer
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const path = require('path');
            const data = fs.readFileSync(path.join('${{github.workspace}}', 'test.json'));
            let parsed = JSON.parse(data);
            return parsed.customer;
            
      - name: Get result
        run: echo "${{steps.getcustomer.outputs.result}}"
        
  
      - name: Echo commit SHA
        run: echo $(git rev-parse HEAD)


  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Get result
        if: ${{ github.event.inputs.dojob2 == 'true' }}
        run: echo "job2 ran"


  job3:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - uses: ./.github/composite-actions/deliver-release
        if: ${{ github.event.inputs.test2ReleaseName != '' }}
        with: 
          name: ${{ github.event.inputs.test2ReleaseName }}
          githubRepository: johannesnormannjensen/test2
          releaseZip: "${{ github.workspace }}/somezipfile.zip"
          pat: ${{ secrets.pat }}
