name: Do the thing

on: 
  workflow_dispatch:
    inputs:
      dojob2:
        description: Should job2 be run
        type: boolean
        default: false
        required: true 
      test2ReleaseName:
        description: Do a release to test2 with this name
        type: string
        required: false 
jobs:



  customers:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      
      - uses: ./.github/composite-actions/customers 
        id: customers
        name: Get customers


  job1:
    runs-on: ubuntu-latest
    needs: customers
      
    strategy:
      matrix:
        customer: ${{ fromJson(needs.customers.outputs.customers) }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Get result
        run: echo "${{ matrix.customer }}"


  job2:
    runs-on: ubuntu-latest
    needs: [customers]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Print result
        run: echo "${{ fromJSON(needs.customers.outputs.customers) }}"
      
      - uses: ./.github/composite-actions/take-customers 
        name: Print customers
        id: print-customers
        with: 
          customers: ${{ needs.customers.outputs.customers }}
        
        
