name: Do the thing

on: 
  workflow_dispatch:
    inputs:
      dojob2:
        description: Should job2 be run
        type: boolean
        default: false
        required: true 
      test2ReleaseName:
        description: Do a release to test2 with this name
        type: string
        required: false 
jobs:

  checkout-job:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: Checkout files except .github
        uses: actions/checkout@v2
        with: 
          filter: |
            .github
      
      - name: List root dir
        run: |
          ls -la .

      - name: Checkout only .github
        uses: actions/checkout@v2
        with: 
          sparse-checkout: |
            .github
      
      - name: List root dir
        run: |
          ls -la .
