name: Do the thing

on: 
  workflow_dispatch:
  
jobs:

  checkout-job:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
      - name: Checkout files except .github
        uses: actions/checkout@v4
      
      - name: List root dir
        run: |
          ls -la .

      - name: Checkout only .github
        uses: actions/checkout@v4
        with: 
          clean: false
          ref: develop
          sparse-checkout: |
            .github
      
      - name: List root dir
        run: |
          ls -la .
