name: Do the thing

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'The name'     
        required: true
        default: 'Bob' 

jobs:
  dothehello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set the vars
        uses: ./.github/actions/hello
        with:
          name: ${{ github.event.inputs.name }}
          
      - name: Echo the vars
        run: |
          echo 'HELLOWITHYOU'
          echo ${{ env.HELLOWITHYOU }}
            
