name: PR Labeler

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            console.log({pr});

            const issue_number = context.payload.pull_request.number;
            const hasLabels = false;
            
            if (hasLabels) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                labels,
              })
            }
      - id: foo
        uses: johannesnormannjensen/test/.github/actions/hello-world-composite@main
        with:
          who-to-greet: 'Mona the Octocat'
            

