name: PR Labeler

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const { title } = context.payload.pull_request
            
            const labelToMatches = {
              'pr:build': ['build'],
              'pr:ci': ['ci'],
              'pr:chore': ['chore'],
              'pr:documentation': ['docs'],
              'pr:feature': ['feat', 'feature'],
              'pr:bugfix': ['fix', 'bugfix'],
              'pr:improvement': ['impr'],
              'pr:performance': ['perf'],
              'pr:refactor': ['refact'],
              'pr:revert': ['revert'],
              'pr:style': ['style'],
              'pr:test': ['test'],
              'pr:hotfix': ['hotfix'],
            };
            
            const labels = [];

            const titleLabel = title && Object.entries(labelToMatches).find(([label,matches]) => matches.some(match => title.startsWith(match)) && label);
            if(titleLabel) {
              labels.push(titleLabel)
            }
            
            const branchName = context.payload.pull_request.head.ref;
            const shouldDeleteOnMerge = titleLabel && branchName.includes('release') === false
            if(shouldDeleteOnMerge) {
              labels.push('pr:delete on merge');
            }
            
            if (labels.length) {
              const issue_number = context.payload.pull_request.number;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                labels,
              });
            }
            
            if(!labels.length) {
              core.setFailed('PR title does not follow contributing rules! \nGo to https://github.com/johannesnormannjensen/test/wiki for contributing rules')
            }
