name: PR Labeler

on: 
  pull_request:

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref
            
            const nameToLabel: Record<string, string> = {
              feature: 'pr:feature',
              chore: 'pr:chore',
              bugfix: 'pr:bugfix',
              hotfix: 'pr:hotfix',
            }

            const label = branchName.includes('/') && nameToLabel[branchName.split('/')[0]]

            if (label) {
              await github.rest.issues.addLabels({
                ...context.repo,
                number: context.payload.pull_request.number,
                labels: [label],
              })
            }
            

