name: Pull Request Merged
on:
  pull_request:
    types: [opened, reopened, synchronize]
    # types: [closed]

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest

    if: ${{ contains(github.event.pull_request.labels.*.name, 'pr-feature') || contains(github.event.pull_request.labels.*.name, 'pr-bugfix') }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("heads/" + `${{github.event.pull_request.head.ref}}`)

# github.rest.git.deleteRef({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   ref: "heads/" + `${{github.event.pull_request.head.ref}}`
# })
