name: Create Release

on:
  push:
    tags:
      - "hypercare/*/v*.*.*"
      - "prerelease/v*.*.*"
      - "release/v*.*.*"

jobs:
  
  package-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          [
            "hej",
            "med",
            "dig"
          ]

    steps:
      
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Extract tag name
        id: tag
        uses: actions/github-script@6
        with:
          result-encoding: string
          script: |
            const splits = context.payload.ref.split('/');
            return splits[splits.length -1];
    
      - name: Create file
        run: |
          mkdir -p etdir/etsubdir
          echo "${{ matrix.configuration }}" >> etdir/enfil.txt
          echo "${{ matrix.configuration }}" >> etdir/etsubdir/enfiltil.txt
          
        
      - name: Zip etdir
        run: |
          zip -r etdir-${{ matrix.configuration }}-${{ steps.tag.outputs.result }}.zip etdir/
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            etdir-${{ matrix.configuration }}-${{ steps.tag.outputs.result }}.zip
