name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  
  package-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          [
            "hej",
            "med",
            "dig"
          ]

    steps:
    
      - name: Extract tag name
        id: tag
        uses: actions/github-script@v6
        with:
          script: |
            return context.payload.ref.replace('refs/tags/', '');

      - name: Create file
        run: |
          echo "${{ matrix.configuration }}" >> ${{ matrix.configuration }}-${{ steps.tag.outputs.result }}.txt
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.configuration }}-${{ steps.tag.outputs.result }}.txt
