name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  
  package-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          [
            "hej",
            "med",
            "dig"
          ]

    steps:
      
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    
      - name: Create file
        run: |
          mkdir -p etdir/etsubdir
          echo "${{ matrix.configuration }}" >> etdir/enfil.txt
          echo "${{ matrix.configuration }}" >> etdir/etsubdir/enfiltil.txt
          
        
      - name: Zip etdir
        run: |
          zip -r etdir-${{ steps.vars.outputs.tag }}.zip etdir/
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            etdir-${{ matrix.configuration }}-${{ steps.vars.outputs.tag }}.zip
