name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  
  package-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          [
            "hej",
            "med",
            "dig"
          ]

    steps:
      
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    
      - name: Create file
        run: |
          mkdir ${{ matrix.configuration }}-${{ steps.vars.outputs.tag }}
          echo "${{ matrix.configuration }}" >> ${{ matrix.configuration }}-${{ steps.vars.outputs.tag }}/enfil.txt
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.configuration }}-${{ steps.vars.outputs.tag }}
