name: Show variables

on: 
  workflow_dispatch:
jobs:

  show-them:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: echo name values
        uses: actions/github-script@v6
        with:
          script: |
            core.info(`env vars`)
            core.info(Object.keys(process.env))
  
