name: Show variables

on: 
  workflow_dispatch:
jobs:

  show-them:
    runs-on: ubuntu-latest
#     env:
#       thevarname: ${{ vars.TEST_ARRAY }}
    
    strategy:
      matrix: 
        arr-value: ${{ fromJSON(vars.TEST_ARRAY)) }}
#         name-value: ${{ fromJSON(vars[env.thevarname]) }}
    
    steps:
      - name: echo name values
        uses: actions/github-script@v6
        with:
          script: |
            core.info(`TESTING_VARIABLES: ${{ vars[matrix.arr-value] }}`);
            core.info(`first name: ${{ fromJSON(vars[matrix.arr-value])[0].name }}`);
#             core.info(`name: ${{ matrix.name-value.name }}`);
#             core.info(`value: ${{ matrix.name-value.value }}`);
