name: Show variables

on: 
  workflow_dispatch:
jobs:

  show-them:
    runs-on: ubuntu-latest
#     env:
#       thevarname: ${{ vars.TEST_ARRAY }}
    
    strategy:
      matrix: 
        arr-value: ${{ fromJSON(vars.TEST_ARRAY) }}
#         name-value: ${{ fromJSON(vars[env.thevarname]) }}
    
    steps:
      
      - name: Checkout files
        uses: actions/checkout@v3
        
      - name: echo name values
        uses: actions/github-script@v6
        with:
          script: |
            core.info(`TESTING_VARIABLES: ${{ vars[matrix.arr-value] }}`);
            core.info(`first name: ${{ fromJSON(vars[matrix.arr-value])[0].name }}`);
            const firstEnabled = JSON.parse('${{ fromJSON(vars[matrix.arr-value])[0].enabled }}');
            core.info(`first is enabed: ${firstEnabled ? 'yes it is' : 'no it is not'}`);

            const first = "${{ hashFiles('**') }}";
            const second = "${{ hashFiles('**', '!UI/**') }}";
                    
            core.info(`first hash: ${first}`);
            core.info(`second hash: ${second}`);
            
#             core.info(`name: ${{ matrix.name-value.name }}`);
#             core.info(`value: ${{ matrix.name-value.value }}`);
