name: Show variables

on: 
  workflow_dispatch:
jobs:

  show-them:
    env:
      thevarname: TESTING_VARIABLES
    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        name-value: ${{ fromJSON(vars[format('{0}', env.thevarname)]) }}
    
    steps:
      - name: echo name values
        uses: actions/github-script@v6
        with:
          script: |
            core.info(`name: ${{ matrix.name-value.name }}`);
            core.info(`value: ${{ matrix.name-value.value }}`);
