name: Show variables

on: 
  workflow_dispatch:
jobs:

  show-them:
    runs-on: ubuntu-latest
    env:
      thevarname: TESTING_VARIABLES
    
#     strategy:
#       matrix: 
#         name-value: ${{ fromJSON(vars[env.thevarname]) }}
    
    steps:
      - name: echo name values
        uses: actions/github-script@v6
        with:
          script: |
            core.info(`TESTING_VARIABLES: ${{ vars[env.thevarname] }}`);
            core.info(`first name: ${{ fromJSON(vars[env.thevarname])[0].name }}`);
#             core.info(`name: ${{ matrix.name-value.name }}`);
#             core.info(`value: ${{ matrix.name-value.value }}`);
