name: Build & Test

on:

  pull_request:
    types: [opened, reopened, synchronize]
    paths: 
      - '!**/*'
      - 'UI/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
