name: Build & Test

on:

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Figure out if files changed
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - '!(UI/**)**'
            ui:
              - 'UI/**'
    
      - name: something
        run: 'echo "No build required" '
        
      - name: somethingelse
        if: steps.changes.outputs.backend == 'true'
        run: 'echo "No build required" '
        
      - name: somethingentirelyelse
        if: ${{ !skipped() }}
        run: 'echo "No build required" '
      
      
