name: Build & Test

on:

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  
  changes:
    runs-on: ubuntu-latest

    outputs:
      backend-changed: ${{ steps.changes.outputs.backend }}
      ui-changed: ${{ steps.changes.outputs.UI }}

    steps:
      - name: Figure out if files changed
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - '!(UI/**)**'
            ui:
              - 'UI/**'

  backend-test:
    runs-on: ubuntu-latest
    needs: [changes]
    
    steps:
      - name: something
        run: 'echo "No build required" '
        
      - name: somethingelse
        if: needs.changes.outputs.backend-changed == 'true'
        run: 'echo "No build required" '
        
      - name: somethingentirelyelse
        if: ${{ success() }}
        run: 'echo "No build required" '
      
      
