name: Build & Test

on:

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
#       - name: Figure out if files changed
#         id: changes
#         uses: dorny/paths-filter@v2
#         with:
#           filters: |
#             backend:
#               - '!(UI/**)**'
#             ui:
#               - 'UI/**'
    
      - name: is-skip
        if: ${{ 'true' == 'false' }}
        run: 'echo "No build required" '
        
      - name: build
        if: ${{ 'true' == 'false' }}
        run: 'echo "Building..." '
        
      - name: test
        if: ${{ 'true' == 'false' }}
#         if: steps.changes.outputs.backend == 'true'
        run: 'echo "Testing..." '
      
      
