name: Test1

on: 
  workflow_dispatch:

env: 
  HELLOWITHYOU: 'something'

jobs:

  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: .github/actions/hello-world-composite
