name: Test1

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'a name'
        type: string
        required: true

env: 
  HELLOWITHYOU: 'something'

jobs:

  checkout-job:
    uses: johannesnormannjensen/test/.github/workflows/callme.yml@${{ github.sha }}
    with:
      name: ${{ github.event.inputs.name }}
