name: Do the thing

on: 
  release:
    types: [edited]
jobs:

    runs-on: ubuntu-latest
    steps:    
    
      - uses: actions/github-script@v6
        id: Log info
        with:
          script: |
            console.log({event: ${{github.event}} });
