name: Release updated

on: 
  release:
    types: [created, edited]
    
jobs:
    
    update-relese:
      runs-on: ubuntu-latest
      
      
      steps:    
      
      - uses: ./.github/actions/update-release 
        id: update-release-body
        name: Update release body
        with: 
          token: $${{ github.token }}
