name: Release updated

on: 
  release:
    types: [created, edited]
    
jobs:
    
    update-release:
      runs-on: ubuntu-latest
      
      
      steps:    
      - name: Checkout files
        uses: actions/checkout@v3
      
      - uses: ./.github/actions/update-release 
        id: update-release-body
        name: Update release body
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
