name: Release updated

on: 
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]
    
jobs:
    
    update-relese:
      runs-on: ubuntu-latest
      
      steps:    
        - uses: actions/github-script@v6
          id: Log info
          with:
            script: |
              console.log({event: ${{github.event}} });
