name: Release updated

on: 
  release:
    types: [created, edited]
    
jobs:
    
    update-relese:
      runs-on: ubuntu-latest
      
      steps:    
        - uses: actions/github-script@v6
          with:
            script: |
              console.log({context: JSON.stringify(context)});
